### PR TITLE
Fix expired file selection

### PR DESCRIPTION
**Pull request by KolyaKorruptis**
The previous code assumed that the scheduled task would run daily at 12:00. None of these are necessarily true.

### CODE REVIEW

**Comment by MissAllSunday** [comment]
So sorry I didn't saw this earlier, will take a look at it, thank you for your submission!

**Comment by MissAllSunday** [comment]
OK I got some time to see this and I'm still not so sure if I understand this change completely.

The ranges are all unix timestamps so changing one of then to 1 will mean the range will only be decreased by 1 millisecond which is very low.

The code indeed assume the scheduled task will be performed at 12:00 and an user can indeed change that time and the code should adapt to that since it doesn't use hardcoded times but instead it uses relative times, meaning it doens't matter if the scheduled task is run at 12 or 14 hours.

**Comment by KolyaKorruptis** [comment]
Look at your code where you are using these values:
WHERE expire_date BETWEEN {int:range_to} AND {int:range_from}

You are deleting only those attachments whose expire date is between 12h in the past and 12h in the future. 
But we want to expire ALL attachments whose expire date lies in the past (and none in the future). Therefore we check from the beginning of unix time to now.

**Comment by MissAllSunday** [comment]
OK, I see the issue, it is indeed looking for a 24 hours period in the future, but the code shouldnt have to be changed to 1, it should need to be changed to  just time() and time() - (12_60_60)

$range_to = time() - (12_60_60);
$range_from = time();

This will get a 24 hour past range period.

**Comment by KolyaKorruptis** [comment]
That's checking 2101 minutes into the past. 
But the user might run this task every week. Then we will miss lots of expired attachments.
He could even disable the task for a while...
Why not just check the whole past time?

**Comment by KolyaKorruptis** [comment]
Okay, I see you probably meant: `$range_to = time() - (12*60*60);`
That is checking 12 hours into the past. It won't even work when the task runs daily. Much less when it runs weekly or monthly.

**Comment by MissAllSunday** [comment]
Oh, no, thats the silly markdown parser...

``` php
    $range_to = time() - (12*60*60);
    $range_from = time();
}
```

Yeah it should be changed to just 3600.

The scheduled task shouldn't be changed to be honest, not that many people actually change the scheduled timeframe or even know how to do it.

A range too large could cause issues with the server, checking the entire past of the forum can choke the server too, just imagine if this mod is been installed ans run for the first time in a forum with lots and lots of attachments?

A daily checks keeps the forum clean and up to date without adding too much stress on the server.

**Comment by MissAllSunday** [comment]
On the other hand I remember I did explicitly use

``` php
    $range_to = time() - (12*60*60);
    $range_from = time() + (12*60*60);
```

12 hours past and 12 hours in the future for a reason, can't really remember why exactly. Probably because of time server configurations.

**Comment by KolyaKorruptis** [comment]
If the mod is installed first time the existing attachments won't have an expiry date. So the check will go sweet and fast.
We can not decide whether the user should change the scheduled task period. It is an available option in vanilla SMF, so I think we should honour it.

**Comment by KolyaKorruptis** [comment]
I can tell you from experience that the mod had missed hundreds of attachments on my server, which were all cleaned up after I changed the code.
This won't usually happen though. If the mod always catches all expired attachments, it will only be a few usually.

**Comment by MissAllSunday** [comment]
The user shouldn't change the scheduled task, there might be an option to do it but it doesn't mean this mod needs to follow that up, if there was a way to disable that feature I would have added it.  People usually do not know what to change or even know if they have to change it.  If this is left for the average user to decide, I will get flooded with questions such as "why is this mod killing my server" when the user decided to change this scheduled task to be run every minute or so...

I'll be willing to change the period to 3600 past but thats about it, I won't change the range period to a longer time as that will only create further issues, misconfigurations and overall confusion.

There is also the actual attachment period expiration which has to be taken into account too, a one week attachment cannot be erased a day after it was posted, thats why the range period needs to be pretty close, if the range period is rise to a week or a month, that would mean an attachment set to be deleted within this current week/month might get deleted earlier because it was caught in the queries range.

If you changed the scheduled timeframe then of course the mod missed a bunch of attachments, the mod simply cannot operate to whatever timeframe an user choses for its scheduled task, it needs to stay uniform across time to fully and accurately get an attachment timeframe.

**Comment by KolyaKorruptis** [comment]
> if the range period is rise to a week or a month, that would mean an attachment set to be deleted within this current week/month might get deleted earlier because it was caught in the queries range.

Attachments have a specific expiration date and when that date is in the past they may be deleted. So a one week attachment will never be erased a day after it was posted, because it's expiration date would be in the future. This is your whole expire date check:

```
$now = time();
DELETE
WHERE expire_date < $now
```

The one comparison is softer on MySQL than the BETWEEN clause (which is two comparisons) and it will never miss any expired attachments.

**Comment by MissAllSunday** [comment]
The problem is not that query, the between transaction is trivial, the problem is the actual attachment deletion.

The bigger the range, more files will be caught and more files will get deleted, deleting an attachment is a server intensive action, deleting multiple attachments on a request via scheduled task can make the server crash.

Thus, keeping the check to a 24 hour period will reduce the number of files to get deleted and instead of deleting everything on a single transaction, the mod instead deletes a fraction each time the scheduled task gets executed, hence the between range check, seriously, I just didn't randomly used a between comparison and limited the range to 24 hours out of the blue...

> Attachments have a specific expiration date and when that date is in the past they may be deleted. >So a one week attachment will never be erased a day after it was posted, because it's expiration >date would be in the future. This is your whole expire date check:

Yes.. that is assuming the scheduled task will always be performed each day...  BUT if the scheduled task gets performed each week or each month, some attachments will get deleted sooner/later than they need to be.

If the scheduled task gets set to run once a week and there is an attachment with an expiration date pointing out to the start of that week, that attachment will only be deleted when the scheduled task gets run at the end of the week, meaning that attachment will enjoy 6 full extra days until it gets deleted.

It gets worse if the scheduled task gets set to once a month.

If the scheduled task timeframe gets constantly changed then there wont be any solid ground to make time comparisons and a lot of attachments will start to get lost.

If I do what you you are asking, the query will collect every attachment in a week period or a full month period, resulting in a large bunch of attachments to be deleted and the server will simply timeout.

The only way this could work is if the scheduled task gets set to once a day and never be changed, which is what the mod already does anyway...

**Comment by KolyaKorruptis** [comment]
The goal of this mod is to delete expired attachments. I understand that in some situations more attachments have to be deleted than in others and that this might put a strain on the server.

If you want to protect such weak servers you can add a LIMIT to the MySQL query and repeat the query until no more results are fetched. 

Simply leaving the expired attachments on the server is not a good solution. Because it's missing the goal of this mod.

**Comment by MissAllSunday** [comment]
This mod is NOT leaving attachments in the server. The mod works as intended and if you keep a steady scheduled timeframe no attachments should be skipped. The mod will work just fine with a scheduled task set to a 24 hour period.

If you modified the scheduled task timeframe then thats a different matter altogether, the mod will not work if you change that behavior but it is not something this mod needs to solve though.

**Comment by KolyaKorruptis** [comment]
This mod left hundreds of attachments on my server, because the range it selects is from -12h to +12h. That's a clear bug in its core functionality, which I proposed a fix for. 
Considering that I paid you to write this mod, one would think you would be interested in fixing it. But apparently you're more interested in trying to prove me wrong.
You're a good programmer, but your pride gets in your way.

**Comment by MissAllSunday** [comment]
Please answer me this clearly with a simply YES or NO.

Did you change the scheduled task to other timeframe different than 24 hours?

If yes, then thats the issue, the mod, as I already explained, will not work that way.

This has nothing to do with pride and I am more than willing to fix any issue on this mod BUT, your issue has been caused by you misusing the mod. As much as I would want to fix that I cannot fix it as it is not a bug within the mod itself. Can't really add support for different scheduled task timeframes, I already explain to you why.

I am not interested on proving you wrong, all I have been doing is explaining why your fix will not really do anything and will not be merged into the mod and its kinda sad that after all my explanations you still think there is a bug on this mod.

So please do not try to use the "I pay you" card, like I have said to you multiple times, I DO provide support and bug fixes for all my paid customizations, however, this particular issue has been caused by the mod been misused, thus it is not really a true bug and I can't fix people misusing the mod, sorry.

Since you already deleted all the "missed" attachment, you can safely go back to a 24 hour period and the mod will start behaving normally like it should have been. Thus, no need for any change in the code.

Lastly, if the mod left hundreds of attachments in your server you should have contacted me about it, not trying to fix it yourself or better yet, ask me if changing the scheduled task will have any impact on the mod itself, that would have avoided all this mess.

I'm really sorry you think I don't want to fix this, its rather sad since I have always been there for any custom job I ever did, but I think it is important to differentiate a real bug from a mod been misused.

**Comment by KolyaKorruptis** [comment]
No, I have never changed the schedule of the mod. It has always been set to one day.
At some point I noticed that certain attachments were never removed, although they had long expired.
I then changed the code as proposed in this pull request. When I manually ran the task after this change hundreds of expired attachments were deleted in one go. It didn't crash my server by the way, although it is weak with 1GB RAM and 4000MHz CPU.

As I explained, your code tries to delete attachments within a timeframe from -12h to +12h. So half of the timeframe lies in the future. I guess it's pretty clear that it will delete attachments too early this way. But apparently you have a hard time imagining how it could miss attachments. Here's how: 

I post an attachment at 11:00 in the morning with a one day expire period. 
The scheduled task runs at midnight. It reaches back only 12 hours (til noon) and misses the attachment. 
The scheduled task of the previous day could not delete my attachment, because it had not been posted yet. And the scheduled task of the next day will certainly not catch it.
This is what happens when you try to delete future attachments. The mod deletes files that haven't expired yet and misses attachments that it should delete. 

Now you wrote this mod for a forum software named SMF. This software allows admins to change the intervals of scheduled tasks via the normal admin interface. How does this constitute a "misuse of this mod"?

You have the chance here to squash two problems:
1. Unintended deletion of attachments that have not expired yet
2. Expired attachments missed and left on the server

I contacted you about this problem on April 4, as soon as I found out. And I proposed a valid fix. You took more than two months to reply and all you're doing now is discuss whether there even is a problem or if it's my misuse of the mod. Good going on closing this issue by the way.

**Comment by MissAllSunday** [comment]
I receive large amounts of notifications, mostly from SMF 2.1 repo, it is pretty easy to miss these notifications, github didn't sent me an email either.

The best way to contact me would have been via my email address. Thats how every single client has ever contacted me, its the correct and only way to receive support from me fro any custom job.

> Now you wrote this mod for a forum software named SMF. This software allows admins to change the intervals of scheduled tasks via the normal admin interface. How does this constitute a "misuse of this mod"?

The scheduled task manager indeed allows admins to change the intervals, that doesn't mean you have to, specially if you do not know the consequences of doing so. I already explained this to you. I already said if I could disable that option I would have, If it depended on me I would have provided a cronjob script and not rely on SMF scheduled task but it doesn't depend on me, I work with what I was told to build using the tools I have available. So how about trying to read what I'm saying instead of bashing me?

> But apparently you have a hard time imagining how it could miss attachments

Again with the bashing, not sure if this is a good way to keep up this conversation.  I fully understand it sets the range to 12 hours past and 12 in the future. I fully understand why you think the proposed change will fix this issue, I've been trying to make you understand that changing it will not solve the issue for everyone using this mod.

Please DO try to understand, yes you ordered this mod but the moment it was set as open source it means I have to keep it as compatible as possible with a large amounts of different server configurations and crappy hostings.  On other words, the mod no longer can be suited and changed to fill your unique requirements, it has to cover SMF userbase.

Best thing I can do is to create a new branch just for you and add changes to that branch just for you and your unique server configuration or say so and I will shut this mod down and make it a close source mod just for you, that way every change made to this mod will solely be for you and your requirements, if you want to delete all attachments at once and your server doesn't complain about it then great, will push the change and send you an updated zip package via email.

**Comment by MissAllSunday** [comment]
OK, I'm going to explain the -12 +12 hours range just one more time:

Using the same example you gave me before:

> I post an attachment at 11:00 in the morning with a one day expire period. 
> The scheduled task runs at midnight. It reaches back only 12 hours (til noon) and misses the attachment.
> The scheduled task of the previous day could not delete my attachment, because it had not been posted yet. And the scheduled task of the next day will certainly not catch it.
> This is what happens when you try to delete future attachments. The mod deletes files that haven't expired yet and misses attachments that it should delete.

And a simply "timeline" to help illustrate the example:

relative timeframes

The attachment was post at 11am with a 24 hour expire date.
The scheduled task runs every day at midnight.
The script has a -12 and a +12 range period:

12pm - 12 = 12am
12pm + 12 = 12am

The day the 11am attachment was made, that same day a scheduled task is run at midnight and it will cover the past 12 hours as well as the next 12 hours:

The attachment is covered since 11am < 12am.

Since the attachment expire day is always set to a FUTURE DATE, the scheduled task rant that same day will catch that expiration day since it has to be deleted at 11am and the scheduled task will cover up to 12am that same day, meaning its covered.

So no, one day attachment will not get lost, they will still be covered by the next scheduled task.

If the attachment expire day is set to 1pm, then the very first one scheduled task will miss it BUT the next scheduled task will catch it. Remember, each scheduled task covers one half of a day, the NEXT one covers the OTHER HALF, meaning THE ENTIRE DAY is fully covered by 2 scheduled task.

So, the scheduled time can be changed (the hour where the scheduled task is run) BUT the scheduled time period (24 hours) shouldn't.

Now, these are the reasons why I DELIVERATED chose to use that system:
- SMF scheduled task IS NOT a cronjob, it doesn't run exactly at the hour it is set to run simply because php cannot do that, instead, SMF relies on someone triggering a request to your forum to be able to execute scheduled tasks.  This means the actual task will almost NEVER be runned at exactly midnight unless someone, an user or a bot enters your forum at exactly that time.

The more visits your forum gets the more accurate the scheduled task became but they will never be run exactly at the given hour, again, SMf scheduled task are not cronjobs.
- Server and users time zone differences. I need to take into consideration any difference in timezones people might have,it is not always the case of people being on the same timezone the server is.

So yes, I am aware of this -12 + 12 range period, I also know it is not perfect and has a few caveats, for example, those attachments posted between the previous 12 hours and the first time the scheduled time was EVER rant, those attachments will indeed, not be deleted. BUT thats the only time epriod attachments will be lose, that one time only 12 hours period.

It is fragile, it depends on the scheduled task been tidily kept at 24 hours timeframe and be rant always, one scheduled task not been run and the script will start skipping attachments.

Yes, changing the query to grab all attachments at once will solve this BUT as I already said, that cannot be fully implemented on a large portion of crappy servers and yes SMF, due to its free nature, it is often installed on free or very cheap servers and it is just as you said it, I build this mod for SMF and I SHALL comply with SMF's nature, this includes be aware and support the most crappy hostings every known.

So there you have it, these are the reasons why your code change will not be implemented.  As I told you before, I can always shut down the mod from here and turned into a custom script just for you, I have no issues with it, in fact I will be kinda relief by that, not because I will stop providing free support for this (this mod is not that popular) but because I will no longer have to care about been compliant with crappy hostings.

If you want to turn this into a custom job just for you then I will suggest you a cronjob and will agree with the changes you implemented, the cronjob will make sure the deletion process gets done exactly at the time its been told to run and the query will delete all past attachments anyway, your server won't complain about it and everyone will be happily aver after...

**Pull request closed without merging**
